In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
arr=np.arange(10)
arr=arr[arr%2==0]
print(arr)

[0 2 4 6 8]


In [3]:
arr=np.random.randint(1,100,size=(3,4))
arr[1:, 1:]=0
arr

array([[81, 26, 38, 63],
       [ 6,  0,  0,  0],
       [47,  0,  0,  0]])

In [4]:
np.diag([1,1,1,1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [5]:
# 1. Flatten the array into a 1D array.
arr = np.array([[3, 6, 9], 
                [1, 5, 8], 
                [2, 7, 10]])
arr=arr.flatten()
arr

array([ 3,  6,  9,  1,  5,  8,  2,  7, 10])

In [6]:
# 2. Replace all even values in the array with 0. 
arr[arr%2==0]=0
arr

array([3, 0, 9, 1, 5, 0, 0, 7, 0])

In [7]:
# 3. Reshape the array back to a 3x3 matrix. 
arr=arr.reshape(3,3)
arr

array([[3, 0, 9],
       [1, 5, 0],
       [0, 7, 0]])

In [8]:
arr = np.array([1, 3, 5, 7, 9, 11])
def fun(array):
    mean=array.mean()
    print(mean)
    array=np.where(array>mean,"High","Low")
    return array    

In [9]:
fun(arr)

6.0


array(['Low', 'Low', 'Low', 'High', 'High', 'High'], dtype='<U4')

In [10]:
df = pd.DataFrame({
    		'A': [1, 2, 3],
    		'B': [4, 5, 6]
	})
df['C'] = df['A'] + df['B']
df

A  B  C
0  1  4  5
1  2  5  7
2  3  6  9

In [11]:
data = {
    		'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    		'Math': [85, 90, 88, 92, 78],
    		'English': [79, 88, 91, 85, 80],
    		'Science': [92, 85, 89, 94, 81]
		}
df=pd.DataFrame(data)
df

Name  Math  English  Science
0    Alice    85       79       92
1      Bob    90       88       85
2  Charlie    88       91       89
3    David    92       85       94
4      Eve    78       80       81

In [12]:
df['Average']=(df.Math+df.English+df.Science)/3
df['Sum']=(df.Math+df.English+df.Science)
print(df)
maximum=df.Average.max()
minimum=df.Average.min()
print("David got maximum: ",maximum)
print("Eve got minimum: ",minimum)

      Name  Math  English  Science    Average  Sum
0    Alice    85       79       92  85.333333  256
1      Bob    90       88       85  87.666667  263
2  Charlie    88       91       89  89.333333  268
3    David    92       85       94  90.333333  271
4      Eve    78       80       81  79.666667  239
David got maximum:  90.33333333333333
Eve got minimum:  79.66666666666667


In [13]:
import pandas as pd
sales_data = {
    		'Product': ['A', 'B', 'C', 'D', 'E'],
    		'Sales_Q1': [100, 150, 200, 130, 180],
    		'Sales_Q2': [120, 160, 210, 150, 170],
    		'Sales_Q3': [110, 180, 220, 140, 190],
    		'Sales_Q4': [130, 170, 250, 120, 160]
		}
df_sales = pd.DataFrame(sales_data)
df_sales

Product  Sales_Q1  Sales_Q2  Sales_Q3  Sales_Q4
0       A       100       120       110       130
1       B       150       160       180       170
2       C       200       210       220       250
3       D       130       150       140       120
4       E       180       170       190       160

In [14]:
df_sales["total_annual_sales"]=df_sales.Sales_Q1+df_sales.Sales_Q2+df_sales.Sales_Q3+df_sales.Sales_Q4
df_sales["GrowthQ1toQ4"]=((df_sales.Sales_Q4-df_sales.Sales_Q1)/df_sales.Sales_Q1)*100
print(df_sales)
maximum=df_sales.total_annual_sales.max()
highpercentage=df_sales.GrowthQ1toQ4.max()
df1=df_sales[df_sales.total_annual_sales==maximum]
df2=df_sales[df_sales.GrowthQ1toQ4==highpercentage]
print(df1)
print(df2)

  Product  Sales_Q1  Sales_Q2  Sales_Q3  Sales_Q4  total_annual_sales  \
0       A       100       120       110       130                 460   
1       B       150       160       180       170                 660   
2       C       200       210       220       250                 880   
3       D       130       150       140       120                 540   
4       E       180       170       190       160                 700   

   GrowthQ1toQ4  
0     30.000000  
1     13.333333  
2     25.000000  
3     -7.692308  
4    -11.111111  
  Product  Sales_Q1  Sales_Q2  Sales_Q3  Sales_Q4  total_annual_sales  \
2       C       200       210       220       250                 880   

   GrowthQ1toQ4  
2          25.0  
  Product  Sales_Q1  Sales_Q2  Sales_Q3  Sales_Q4  total_annual_sales  \
0       A       100       120       110       130                 460   

   GrowthQ1toQ4  
0          30.0  


In [15]:
employee_data = {
    		'Name': ['John', 'Jane', 'Mary', 'Paul', 'Anna'],
    		'Age': [28, 35, 40, 45, 22],
    		'Department': ['HR', 'Finance', 'IT', 'Finance', 'HR'],
    		'Salary': [50000, 60000, 70000, 75000, 45000]}
df_employee = pd.DataFrame(employee_data)
df_employee["Age_Group"]=df_employee.Age
print("before modification:")
print(df_employee)
conditions = {
    "Young": df_employee["Age_Group"]<30,
    "Middle": (df_employee["Age_Group"]>30) & (df_employee["Age_Group"]<=40),
    "Senior":df_employee["Age_Group"]>40
}
df_employee["Age_Group"]= np.select(conditions.values(),conditions.keys(),default=df_employee["Age_Group"])
print("After modification:")
print(df_employee)
print(df_employee.groupby("Department")["Salary"].mean())
print(df_employee[df_employee.Salary==df_employee.Salary.max()])

before modification:
   Name  Age Department  Salary  Age_Group
0  John   28         HR   50000         28
1  Jane   35    Finance   60000         35
2  Mary   40         IT   70000         40
3  Paul   45    Finance   75000         45
4  Anna   22         HR   45000         22
After modification:
   Name  Age Department  Salary Age_Group
0  John   28         HR   50000     Young
1  Jane   35    Finance   60000    Middle
2  Mary   40         IT   70000    Middle
3  Paul   45    Finance   75000    Senior
4  Anna   22         HR   45000     Young
Department
Finance    67500.0
HR         47500.0
IT         70000.0
Name: Salary, dtype: float64
   Name  Age Department  Salary Age_Group
3  Paul   45    Finance   75000    Senior


In [63]:
product_data = {
    		'Product': ['Apple', 'Banana', 'Carrot', 'Date', 'Eggplant'],
    		'Price': [2.5, 1.2, 3.0, 2.8, 1.5],
    		'Category': ['Fruit', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable']
}
df_product = pd.DataFrame(product_data)
df_product

Product  Price   Category
0     Apple    2.5      Fruit
1    Banana    1.2      Fruit
2    Carrot    3.0  Vegetable
3      Date    2.8      Fruit
4  Eggplant    1.5  Vegetable

In [64]:
# 1. Group the products by their Category and calculate the average price per category.
df_product.groupby("Category")["Price"].mean()

Category
Fruit        2.166667
Vegetable    2.250000
Name: Price, dtype: float64

In [65]:
# 2.Filter the products that cost more than 2.5 and are classified as Fruit.
df_product[(df_product["Price"]>2.5) & (df_product["Category"]=="Fruit")]

Product  Price Category
3    Date    2.8    Fruit

In [75]:
# 3. Sort the products by price in descending order and reset the index.
df_product.sort_values("Price",ascending=False).reset_index(drop=True)

Product  Price   Category
0    Carrot    3.0  Vegetable
1      Date    2.8      Fruit
2     Apple    2.5      Fruit
3  Eggplant    1.5  Vegetable
4    Banana    1.2      Fruit

In [79]:
data = {
    		'Age': [23, 45, 56, 67, 34, 23, 45, 67],
    		'Salary': [50000, 60000, 70000, 80000, 55000, 45000, 65000, 75000]
}
df = pd.DataFrame(data)
df

Age  Salary
0   23   50000
1   45   60000
2   56   70000
3   67   80000
4   34   55000
5   23   45000
6   45   65000
7   67   75000

In [84]:
# 1. Split the data into features (X) and target (y) where X is the Age and y is the Salary.
y=df.Salary
x=df.drop("Salary",axis=1)
print(x,"\n",y)

   Age
0   23
1   45
2   56
3   67
4   34
5   23
6   45
7   67 
 0    50000
1    60000
2    70000
3    80000
4    55000
5    45000
6    65000
7    75000
Name: Salary, dtype: int64
